app/network/forms.py
# -*- coding: utf-8 -*-
"""
app.network.forms
~~~~~~~~~~~~~~~~~

This module defines the network blueprint forms.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from flask_login import current_user
from wtforms import (SelectField, StringField, TextAreaField, IntegerField,
                     SelectMultipleField, BooleanField, validators)
from ..helpers import CSEntryForm
from ..validators import (Unique, RegexpList, IPNetwork, HOST_NAME_RE,
                          VLAN_NAME_RE, MAC_ADDRESS_RE)
from .. import utils, models


def validate_tags(form, field):
    choices = dict(field.choices)
    for tag_id in field.data:
        tag_name = choices.get(tag_id)
        if tag_name == 'gateway':
            network = models.Network.query.get(form.network_id.data)
            existing_gateway = network.gateway()
            if existing_gateway is not None:
                raise validators.ValidationError(f'A gateway is already defined for network {network}: {existing_gateway}')


class NoValidateSelectField(SelectField):
    """SelectField with no choices validation

    By default a SelectField tries to validate the selected value
    against the list of choices. This is not possible when the choices
    are dynamically created on the browser side.
    """

    def pre_validate(self, form):
        pass


class NetworkScopeForm(CSEntryForm):
    name = StringField('Name',
                       description='name must be 3-25 characters long and contain only letters, numbers and dash',
                       validators=[validators.InputRequired(),
                                   validators.Regexp(VLAN_NAME_RE),
                                   Unique(models.NetworkScope, column='name')])
    description = TextAreaField('Description')
    first_vlan = IntegerField('First vlan')
    last_vlan = IntegerField('Last vlan')
    supernet = StringField('Supernet',
                           validators=[validators.InputRequired(),
                                       IPNetwork()])


class NetworkForm(CSEntryForm):
    scope_id = SelectField('Network Scope')
    vlan_name = StringField('Vlan name',
                            description='vlan name must be 3-25 characters long and contain only letters, numbers and dash',
                            validators=[validators.InputRequired(),
                                        validators.Regexp(VLAN_NAME_RE),
                                        Unique(models.Network, column='vlan_name')])
    vlan_id = NoValidateSelectField('Vlan id', choices=[])
    description = TextAreaField('Description')
    prefix = NoValidateSelectField('Prefix', choices=[])
    address = NoValidateSelectField('Address', choices=[])
    first_ip = NoValidateSelectField('First IP', choices=[])
    last_ip = NoValidateSelectField('Last IP', choices=[])
    admin_only = BooleanField('Admin only')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.scope_id.choices = utils.get_model_choices(models.NetworkScope, attr='name')


class HostForm(CSEntryForm):
    name = StringField('Hostname',
                       description='hostname must be 2-20 characters long and contain only letters, numbers and dash',
                       validators=[validators.InputRequired(),
                                   validators.Regexp(HOST_NAME_RE),
                                   Unique(models.Host)],
                       filters=[utils.lowercase_field])
    type = SelectField('Type', choices=utils.get_choices(('Virtual', 'Physical')))
    description = TextAreaField('Description')
    item_id = SelectField('Item', coerce=utils.coerce_to_str_or_none)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.item_id.choices = utils.get_model_choices(models.Item, allow_none=True, attr='ics_id')


class InterfaceForm(CSEntryForm):
    host_id = SelectField('Host')
    network_id = SelectField('Network')
    # The list of IPs is dynamically created on the browser side
    # depending on the selected network
    ip = NoValidateSelectField('IP', choices=[])
    interface_name = StringField(
        'Interface name',
        description='name must be 2-20 characters long and contain only letters, numbers and dash',
        validators=[validators.InputRequired(),
                    validators.Regexp(HOST_NAME_RE),
                    Unique(models.Interface)],
        filters=[utils.lowercase_field])
    mac_address = StringField(
        'MAC',
        validators=[validators.Optional(),
                    validators.Regexp(MAC_ADDRESS_RE, message='Invalid MAC address')])
    cnames_string = StringField(
        'Cnames',
        description='space separated list of cnames (must be 2-20 characters long and contain only letters, numbers and dash)',
        validators=[validators.Optional(),
                    RegexpList(HOST_NAME_RE)])
    tags = SelectMultipleField('Tags', coerce=utils.coerce_to_str_or_none,
                               validators=[validate_tags])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.host_id.choices = utils.get_model_choices(models.Host)
        if current_user.is_admin:
            network_query = models.Network.query
            tags_query = models.Tag.query
        else:
            network_query = models.Network.query.filter(models.Network.admin_only.is_(False))
            tags_query = models.Tag.query.filter(models.Tag.admin_only.is_(False))
        self.network_id.choices = utils.get_model_choices(models.Network, allow_none=False,
                                                          attr='vlan_name', query=network_query)
        self.tags.choices = utils.get_model_choices(models.Tag, allow_none=True,
                                                    attr='name', query=tags_query)


class HostInterfaceForm(HostForm, InterfaceForm):
    pass

app/network/views.py
# -*- coding: utf-8 -*-
"""
app.network.views
~~~~~~~~~~~~~~~~~

This module implements the network blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
import ipaddress
import sqlalchemy as sa
from flask import (Blueprint, render_template, jsonify, session,
                   redirect, url_for, request, flash, current_app)
from flask_login import login_required
from .forms import (HostForm, InterfaceForm, HostInterfaceForm, NetworkForm,
                    NetworkScopeForm)
from ..extensions import db
from ..decorators import login_groups_accepted
from .. import models, utils, helpers

bp = Blueprint('network', __name__)


@bp.route('/hosts')
@login_required
def list_hosts():
    return render_template('network/hosts.html')


@bp.route('/hosts/create', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def create_host():
    # Try to get the network_id from the session
    # to pre-fill the form with the same network
    try:
        network_id = session['network_id']
    except KeyError:
        # No need to pass request.form when no extra keywords are given
        form = HostInterfaceForm()
    else:
        form = HostInterfaceForm(request.form, network_id=network_id)
    # Remove the host_id field inherited from the InterfaceForm
    # It's not used in this form
    del form.host_id
    if form.validate_on_submit():
        network_id = form.network_id.data
        host = models.Host(name=form.name.data,
                           type=form.type.data,
                           description=form.description.data or None,
                           item_id=form.item_id.data)
        # The total number of tags will always be quite small
        # It's more efficient to retrieve all of them in one query
        # and do the filtering here
        all_tags = models.Tag.query.all()
        tags = [tag for tag in all_tags if str(tag.id) in form.tags.data]
        interface = models.Interface(name=form.interface_name.data,
                                     ip=form.ip.data,
                                     network_id=network_id,
                                     tags=tags)
        interface.cnames = [models.Cname(name=name) for name in form.cnames_string.data.split()]
        helpers.associate_mac_to_interface(form.mac_address.data, interface)
        host.interfaces = [interface]
        current_app.logger.debug(f'Trying to create: {host!r}')
        db.session.add(host)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Host {host} created!', 'success')
        # Save network_id to the session to retrieve it after the redirect
        session['network_id'] = network_id
        return redirect(url_for('network.create_host'))
    return render_template('network/create_host.html', form=form)


@bp.route('/hosts/view/<name>')
@login_required
def view_host(name):
    host = models.Host.query.filter_by(name=name).first_or_404()
    return render_template('network/view_host.html', host=host)


@bp.route('/hosts/edit/<name>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def edit_host(name):
    host = models.Host.query.filter_by(name=name).first_or_404()
    form = HostForm(request.form, obj=host)
    if form.validate_on_submit():
        host.name = form.name.data
        host.type = form.type.data
        host.item_id = form.item_id.data
        host.description = form.description.data or None
        current_app.logger.debug(f'Trying to update: {host!r}')
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Host {host} updated!', 'success')
        return redirect(url_for('network.view_host', name=host.name))
    return render_template('network/edit_host.html', form=form)


@bp.route('/interfaces/create/<hostname>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def create_interface(hostname):
    host = models.Host.query.filter_by(name=hostname).first_or_404()
    form = InterfaceForm(request.form, host_id=host.id, interface_name=host.name)
    if form.validate_on_submit():
        # The total number of tags will always be quite small
        # It's more efficient to retrieve all of them in one query
        # and do the filtering here
        all_tags = models.Tag.query.all()
        tags = [tag for tag in all_tags if str(tag.id) in form.tags.data]
        interface = models.Interface(host_id=host.id,
                                     name=form.interface_name.data,
                                     ip=form.ip.data,
                                     network_id=form.network_id.data,
                                     tags=tags)
        interface.cnames = [models.Cname(name=name) for name in form.cnames_string.data.split()]
        helpers.associate_mac_to_interface(form.mac_address.data, interface)
        current_app.logger.debug(f'Trying to create: {interface!r}')
        db.session.add(interface)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Host {interface} created!', 'success')
        return redirect(url_for('network.create_interface', hostname=hostname))
    return render_template('network/create_interface.html', form=form, hostname=hostname)


@bp.route('/interfaces/edit/<name>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def edit_interface(name):
    interface = models.Interface.query.filter_by(name=name).first_or_404()
    cnames_string = ' '.join([str(cname) for cname in interface.cnames])
    try:
        mac_address = interface.mac.address
    except AttributeError:
        mac_address = ''
    form = InterfaceForm(request.form, obj=interface,
                         interface_name=interface.name,
                         mac_address=mac_address,
                         cnames_string=cnames_string)
    ips = [interface.ip]
    ips.extend([str(address) for address in interface.network.available_ips()])
    form.ip.choices = utils.get_choices(ips)
    if form.validate_on_submit():
        interface.name = form.interface_name.data
        interface.ip = form.ip.data
        interface.network_id = form.network_id.data
        if form.mac_address.data:
            if form.mac_address.data != mac_address:
                # The MAC changed - add the new one to the interface
                # that will remove the association to the previous one
                helpers.associate_mac_to_interface(form.mac_address.data, interface)
            # else: nothing to do (address didn't change)
        else:
            # No MAC associated
            interface.mac_id = None
        # Delete the cnames that have been removed
        new_cnames_string = form.cnames_string.data.split()
        for (index, cname) in enumerate(interface.cnames):
            if cname.name not in new_cnames_string:
                current_app.logger.debug(f'Deleting cname: {cname}')
                # Removing the cname from interface.cnames list will
                # delete it from the database due to the cascade
                # delete-orphan option defined on the model
                del interface.cnames[index]
        # Add new cnames
        for name in new_cnames_string:
            if name not in cnames_string:
                cname = models.Cname(name=name)
                current_app.logger.debug(f'Creating cname: {cname}')
                interface.cnames.append(cname)
        all_tags = models.Tag.query.all()
        tags = [tag for tag in all_tags if str(tag.id) in form.tags.data]
        interface.tags = tags
        current_app.logger.debug(f'Trying to update: {interface!r}')
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Interface {interface} updated!', 'success')
        return redirect(url_for('network.view_host', name=interface.host.name))
    return render_template('network/edit_interface.html', form=form, hostname=interface.host.name)


@bp.route('/interfaces/delete', methods=['POST'])
@login_groups_accepted('admin', 'create')
def delete_interface():
    interface = models.Interface.query.get_or_404(request.form['interface_id'])
    hostname = interface.host.name
    # Deleting the interface will also delete all
    # associated cnames due to the cascade delete option
    # defined on the model
    db.session.delete(interface)
    db.session.commit()
    flash(f'Interface {interface.name} has been deleted', 'success')
    return redirect(url_for('network.view_host', name=hostname))


@bp.route('/scopes')
@login_required
def list_scopes():
    return render_template('network/scopes.html')


@bp.route('/scopes/create', methods=('GET', 'POST'))
@login_groups_accepted('admin')
def create_scope():
    form = NetworkScopeForm()
    if form.validate_on_submit():
        scope = models.NetworkScope(name=form.name.data,
                                    description=form.description.data or None,
                                    first_vlan=form.first_vlan.data,
                                    last_vlan=form.last_vlan.data,
                                    supernet=form.supernet.data)
        current_app.logger.debug(f'Trying to create: {scope!r}')
        db.session.add(scope)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()

app/templates/network/create_host.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Host - CSEntry{% endblock %}

{% block hosts_main %}
  <form id="hostForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, class_="text-lowercase") }}
    {{ render_field(form.type) }}
    {{ render_field(form.description) }}
    {{ render_field(form.item_id, disabled=True) }}
    {{ render_field(form.network_id) }}
    {{ render_field(form.ip) }}
    {{ render_field(form.interface_name, class_="text-lowercase") }}
    {{ render_field(form.mac_address) }}
    {{ render_field(form.cnames_string) }}
    {{ render_field(form.tags) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/create_interface.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Interface - CSEntry{% endblock %}

{% block hosts_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.view_host', name=hostname) }}">View host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.edit_host', name=hostname) }}">Edit host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.create_interface', hostname=hostname) }}">Add interface</a>
    </li>
{% endblock %}


{% block hosts_main %}
  <form id="interfaceForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.host_id, disabled=True) }}
    {{ render_field(form.interface_name, class_="text-lowercase") }}
    {{ render_field(form.network_id) }}
    {{ render_field(form.ip) }}
    {{ render_field(form.mac_address) }}
    {{ render_field(form.cnames_string) }}
    {{ render_field(form.tags) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/create_network.html
{% extends "network/networks.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Network - CSEntry{% endblock %}

{% block networks_main %}
  <form id="networkForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.scope_id) }}
    {{ render_field(form.vlan_name) }}
    {{ render_field(form.vlan_id) }}
    {{ render_field(form.description) }}
    {{ render_field(form.prefix) }}
    {{ render_field(form.address) }}
    {{ render_field(form.first_ip) }}
    {{ render_field(form.last_ip) }}
    {{ render_field(form.admin_only) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/create_scope.html
{% extends "network/scopes.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Network Scope - CSEntry{% endblock %}

{% block scopes_main %}
  <form id="scopeForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    {{ render_field(form.first_vlan) }}
    {{ render_field(form.last_vlan) }}
    {{ render_field(form.supernet) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/edit_host.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Edit Host - CSEntry{% endblock %}

{% block hosts_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.view_host', name=form.name.data) }}">View host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.edit_host', name=form.name.data) }}">Edit host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.create_interface', hostname=form.name.data) }}">Add interface</a>
    </li>
{% endblock %}

{% block hosts_main %}
  <form id="editHostForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, class_="text-lowercase") }}
    {{ render_field(form.type) }}
    {{ render_field(form.description) }}
    {{ render_field(form.item_id, disabled=True) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/edit_interface.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Edit Interface - CSEntry{% endblock %}

{% block hosts_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.view_host', name=hostname) }}">View host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.edit_host', name=hostname) }}">Edit host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.create_interface', hostname=hostname) }}">Add interface</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.edit_interface', name=hostname) }}">Edit interface</a>
    </li>
{% endblock %}


{% block hosts_main %}
  <form id="editInterfaceForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.host_id, disabled=True) }}
    {{ render_field(form.interface_name, class_="text-lowercase") }}
    {{ render_field(form.network_id) }}
    {{ render_field(form.ip) }}
    {{ render_field(form.mac_address) }}
    {{ render_field(form.cnames_string) }}
    {{ render_field(form.tags) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/hosts.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active %}

{% block title %}Hosts - CSEntry{% endblock %}

{% block main %}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/network/hosts")) }}" href="{{ url_for('network.list_hosts') }}">List hosts</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.startswith("/network/hosts/create")) }}" href="{{ url_for('network.create_host') }}">Register new host</a>
    </li>
    {% block hosts_nav %}{% endblock %}
  </ul>

  <br>

  {% block hosts_main %}
  <table id="hosts_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Hostname</th>
        <th>Type</th>
        <th>Description</th>
        <th>Interface name</th>
        <th>Interface IP</th>
        <th>Interface network</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/hosts.js') }}"></script>
{% endblock %}

app/templates/network/networks.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active %}

{% block title %}Networks - CSEntry{% endblock %}

{% block main %}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/network/networks")) }}" href="{{ url_for('network.list_networks') }}">List networks</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.startswith("/network/networks/create")) }}" href="{{ url_for('network.create_network') }}">Register new network</a>
    </li>
    {% block networks_nav %}{% endblock %}
  </ul>

  <br>

  {% block networks_main %}
  <table id="networks_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Network scope</th>
        <th>Vlan name</th>
        <th>Vlan id</th>
        <th>Description</th>
        <th>Address</th>
        <th>First IP</th>
        <th>Last IP</th>
        <th>Admin only</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/networks.js') }}"></script>
{% endblock %}

app/templates/network/scopes.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active %}

{% block title %}Network Scopes - CSEntry{% endblock %}

{% block main %}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/network/scopes")) }}" href="{{ url_for('network.list_scopes') }}">List network scopes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.startswith("/network/scopes/create")) }}" href="{{ url_for('network.create_scope') }}">Register new network scope</a>
    </li>
    {% block scopes_nav %}{% endblock %}
  </ul>

  <br>

  {% block scopes_main %}
  <table id="scopes_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>First vlan</th>
        <th>Last vlan</th>
        <th>Supernet</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/scopes.js') }}"></script>
{% endblock %}

app/templates/network/view_host.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import link_to_item, delete_button_with_confirmation %}

{% block title %}View Host - CSEntry{% endblock %}

{% block hosts_nav %}
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.view_host', name=host.name) }}">View host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.edit_host', name=host.name) }}">Edit host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.create_interface', hostname=host.name) }}">Add interface</a>
    </li>
{% endblock %}

{% block hosts_main %}
  <dl class="row">
    <dt class="col-sm-3">Hostname</dt>
    <dd class="col-sm-9">{{ host.name }}</dd>
    <dt class="col-sm-3">Type</dt>
    <dd class="col-sm-9">{{ host.type }}</dd>
    {% if host.type == 'Physical' %}
    <dt class="col-sm-3">Item</dt>
    <dd class="col-sm-9">{{ link_to_item(host.item) }}</dd>
    {% endif %}
    <dt class="col-sm-3">Description</dt>
    <dd class="col-sm-9">{{ host.description }}</dd>
  </dl>
  <h3>Interfaces</h3>
  <table id="interfaces_table" class="table table-hover table-sm">
    <thead>
      <tr>
        <th width="5%"></th>
        <th>Name</th>
        <th>Cnames</th>
        <th>IP</th>
        <th>MAC</th>
        <th>Network</th>
        <th>Tags</th>
      </tr>
    </thead>
    <tbody>
      {% for interface in host.interfaces %}
      <tr>
        <td class="btn-group mr-2" role="group" aria-label="edit delete interface">
          <a class="btn btn-light" role="button" href="{{ url_for('network.edit_interface', name=interface.name) }}" title="Edit interface">
              <span class="oi oi-pencil" aria-hidden="true"></span>
          </a>
          <form method="POST" action="/network/interfaces/delete">
            <input id="interface_id" name="interface_id" type="hidden" value="{{ interface.id }}">
            {{ delete_button_with_confirmation("Delete interface", "deleteConfirmation-%s" | format(interface.id),
               "Are you sure you want to delete interface %s?" | format(interface.name)) }}
          </form>
        </td>
        <td>{{ interface.name }}</td>
        <td>{{ interface.cnames | join(' ') }}</td>
        <td>{{ interface.ip }}</td>
        <td>{{ interface.mac }}</td>
        <td>{{ interface.network }}</td>
        <td>{{ interface.tags | join(' ') }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%- endblock %}