app/inventory/forms.py
# -*- coding: utf-8 -*-
"""
app.inventory.forms
~~~~~~~~~~~~~~~~~~~

This module defines the inventory blueprint forms.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from wtforms import SelectField, StringField, IntegerField, TextAreaField, validators
from ..helpers import CSEntryForm
from ..validators import Unique, RegexpList, ICS_ID_RE, MAC_ADDRESS_RE
from .. import utils, models


class AttributeForm(CSEntryForm):
    name = StringField('Name', validators=[validators.DataRequired()])
    description = StringField('Description')


class ItemForm(CSEntryForm):
    ics_id = StringField('ICS id',
                         validators=[validators.InputRequired(),
                                     validators.Regexp(ICS_ID_RE),
                                     Unique(models.Item, 'ics_id')])
    serial_number = StringField('Serial number',
                                validators=[validators.InputRequired()])
    quantity = IntegerField('Quantity', default=1,
                            validators=[validators.NumberRange(min=1)])
    manufacturer_id = SelectField('Manufacturer', coerce=utils.coerce_to_str_or_none)
    model_id = SelectField('Model', coerce=utils.coerce_to_str_or_none)
    location_id = SelectField('Location', coerce=utils.coerce_to_str_or_none)
    status_id = SelectField('Status', coerce=utils.coerce_to_str_or_none)
    parent_id = SelectField('Parent', coerce=utils.coerce_to_str_or_none)
    mac_addresses = StringField(
        'MAC addresses',
        description='space separated list of MAC addresses',
        validators=[validators.Optional(),
                    RegexpList(MAC_ADDRESS_RE, message='Invalid MAC address')])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.manufacturer_id.choices = utils.get_model_choices(models.Manufacturer, allow_none=True)
        self.model_id.choices = utils.get_model_choices(models.Model, allow_none=True)
        self.location_id.choices = utils.get_model_choices(models.Location, allow_none=True)
        self.status_id.choices = utils.get_model_choices(models.Status, allow_none=True)
        self.parent_id.choices = utils.get_model_choices(models.Item, allow_none=True, attr='ics_id')


class CommentForm(CSEntryForm):
    body = TextAreaField('Enter your comment:',
                         validators=[validators.DataRequired()])

app/inventory/views.py
# -*- coding: utf-8 -*-
"""
app.inventory.views
~~~~~~~~~~~~~~~~~~~

This module implements the inventory blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
import sqlalchemy as sa
from flask import (Blueprint, render_template, jsonify, session,
                   request, redirect, url_for, flash, current_app)
from flask_login import login_required
from .forms import AttributeForm, ItemForm, CommentForm
from ..extensions import db
from ..decorators import login_groups_accepted
from .. import utils, models

bp = Blueprint('inventory', __name__)


@bp.route('/_retrieve_items')
@login_required
def retrieve_items():
    # Get the parameters from the query string sent by datatables
    draw = int(request.args.get('draw', 0))
    start = int(request.args.get('start', 0))
    per_page = int(request.args.get('length', 20))
    search = request.args.get('search[value]', '')
    order_column = int(request.args.get('order[0][column]', 3))
    if request.args.get('order[0][dir]') == 'desc':
        order_dir = sa.desc
    else:
        order_dir = sa.asc
    # Total number of items before filtering
    nb_items_total = db.session.query(sa.func.count(models.Item.id)).scalar()
    # Construct the query
    query = models.Item.query
    if search:
        if '%' not in search:
            search = f'%{search}%'
        q1 = query.filter(
            sa.or_(
                models.Item.ics_id.like(search),
                models.Item.serial_number.like(search),
            )
        )
        q2 = query.join(models.Item.manufacturer).filter(
            models.Manufacturer.name.like(search))
        q3 = query.join(models.Item.model).filter(
            models.Model.name.like(search))
        q4 = query.join(models.Item.location).filter(
            models.Location.name.like(search))
        q5 = query.join(models.Item.status).filter(
            models.Status.name.like(search))
        q6 = query.join(models.Item.comments).filter(
            models.ItemComment.body.like(search))
        query = q1.union(q2).union(q3).union(q4).union(q5).union(q6)
        nb_items_filtered = query.order_by(None).count()
    else:
        nb_items_filtered = nb_items_total
    # Construct the order_by query
    columns = ('id',
               'ics_id',
               'created_at',
               'updated_at',
               'serial_number',
               'quantity',
               'manufacturer',
               'model',
               'location',
               'status',
               'parent',
               )
    query = query.order_by(order_dir(getattr(models.Item, columns[order_column])))
    # Limit and offset the query
    if per_page != -1:
        query = query.limit(per_page)
    query = query.offset(start)
    data = [
        [item.id,
         item.ics_id,
         utils.format_field(item.created_at),
         utils.format_field(item.updated_at),
         item.serial_number,
         item.quantity,
         utils.format_field(item.manufacturer),
         utils.format_field(item.model),
         utils.format_field(item.location),
         utils.format_field(item.status),
         utils.format_field(item.parent),
         ] for item in query.all()
    ]
    response = {
        'draw': draw,
        'recordsTotal': nb_items_total,
        'recordsFiltered': nb_items_filtered,
        'data': data
    }
    return jsonify(response)


@bp.route('/items')
@login_required
def list_items():
    return render_template('inventory/items.html')


@bp.route('/items/create', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def create_item():
    # The following keys are stored in the session to easily create
    # several identical items
    keys = ('manufacturer_id', 'model_id', 'location_id', 'status_id', 'parent_id')
    settings = {key: session.get(key, '') for key in keys}
    form = ItemForm(request.form, **settings)
    if form.validate_on_submit():
        for key in keys:
            session[key] = getattr(form, key).data
        item = models.Item(ics_id=form.ics_id.data,
                           serial_number=form.serial_number.data,
                           quantity=form.quantity.data,
                           manufacturer_id=form.manufacturer_id.data,
                           model_id=form.model_id.data,
                           location_id=form.location_id.data,
                           status_id=form.status_id.data,
                           parent_id=form.parent_id.data)
        item.macs = [models.Mac(address=address) for address in form.mac_addresses.data.split()]
        current_app.logger.debug(f'Trying to create: {item!r}')
        db.session.add(item)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Item {item} created!', 'success')
        return redirect(url_for('inventory.create_item'))
    return render_template('inventory/create_item.html', form=form)


@bp.route('/items/view/<ics_id>')
@login_required
def view_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    return render_template('inventory/view_item.html', item=item)


@bp.route('/items/comment/<ics_id>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def comment_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    form = CommentForm()
    if form.validate_on_submit():
        comment = models.ItemComment(body=form.body.data,
                                     item_id=item.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('inventory.view_item', ics_id=ics_id))
    return render_template('inventory/comment_item.html', item=item, form=form)


@bp.route('/items/edit/<ics_id>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def edit_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    mac_addresses = ' '.join([str(mac) for mac in item.macs])
    form = ItemForm(request.form, obj=item, mac_addresses=mac_addresses)
    if form.validate_on_submit():
        # Only allow to update temporary ics_id
        if item.ics_id.startswith(current_app.config['TEMPORARY_ICS_ID']):
            item.ics_id = form.ics_id.data
        item.serial_number = form.serial_number.data
        item.quantity = form.quantity.data
        for key in ('manufacturer_id', 'model_id', 'location_id', 'status_id', 'parent_id'):
            setattr(item, key, getattr(form, key).data)
        new_addresses = form.mac_addresses.data.split()
        # Delete the MAC addresses that have been removed
        for (index, mac) in enumerate(item.macs):
            if mac.address not in new_addresses:
                item.macs.pop(index)
                db.session.delete(mac)
        # Add new MAC addresseses
        for address in new_addresses:
            if address not in mac_addresses:
                mac = models.Mac(address=address)
                item.macs.append(mac)
        current_app.logger.debug(f'Trying to update: {item!r}')
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Item {item} updated!', 'success')
        return redirect(url_for('inventory.view_item', ics_id=item.ics_id))
    return render_template('inventory/edit_item.html', form=form)


@bp.route('/qrcodes/<kind>')
@login_required
def qrcodes(kind='Action'):
    try:
        model = getattr(models, kind)
    except AttributeError:
        raise utils.CSEntryError(f"Unknown model '{kind}'", status_code=422)
    items = db.session.query(model).order_by(model.name)
    images = [{'name': item.name,
               'data': item.base64_image()}
              for item in items]
    return render_template('inventory/qrcodes.html', kind=kind, images=images)


@bp.route('/attributes/<kind>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def attributes(kind):
    form = AttributeForm()
    if form.validate_on_submit():
        model = getattr(models, kind)
        new_model = model(name=form.name.data,
                          description=form.description.data or None)
        db.session.add(new_model)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            flash(f'{form.name.data} already exists! {kind} not created.', 'error')
        else:
            flash(f'{kind} {new_model} created!', 'success')
        return redirect(url_for('inventory.attributes', kind=kind))
    return render_template('inventory/attributes.html', kind=kind, form=form)


@bp.route('/_retrieve_attributes_name/<kind>')
@login_required
def retrieve_attributes_name(kind):
    try:
        model = getattr(models, kind)
    except AttributeError:
        raise utils.CSEntryError(f"Unknown model '{kind}'", status_code=422)
    items = db.session.query(model).order_by(model.name)
    data = [(item.name, item.description) for item in items]
    return jsonify(data=data)

app/templates/inventory/attributes.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Attributes - CSEntry{% endblock %}

{% block main %}
  <ul class="nav nav-tabs">
    {% for attribute in ('Manufacturer', 'Model', 'Location') %}
    <li class="nav-item">
      <a class="nav-link {% if attribute == kind %}active{% endif %}" href="{{ url_for('inventory.attributes', kind=attribute) }}">{{ attribute }}</a>
    </li>
    {% endfor %}
  </ul>

  <br>

  <form id="attributeForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Create</button>
      </div>
    </div>
  </form>

  <hr class="separator">

  <table id="attributes_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
  </table>
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/attributes.js') }}"></script>
{% endblock %}

app/templates/inventory/comment_item.html
{% extends "inventory/view_item.html" %}

  {% block comment_item %}
  <form id="CommentForm" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.body.label() }}
      {{ form.body(class_="form-control", rows=5, required=True) }}
      <small class="form-text text-muted">Styling with Markdown is supported using
        <a href="https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax" target="_blank">Showdown</a>.
        A preview is visible below.
      </small>
    </div>
    <div class="card">
      <div class="card-header">
        Comment preview
      </div>
      <div class="card-body" id="commentLivePreview"></div>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-danger" href="{{ url_for('inventory.view_item', ics_id=item.ics_id) }}">Cancel</a>
  </form>
  {% endblock %}

app/templates/inventory/create_item.html
{% extends "inventory/items.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Item - CSEntry{% endblock %}

{% block items_main %}
  <form id="itemForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.ics_id) }}
    {{ render_field(form.serial_number) }}
    {{ render_field(form.quantity) }}
    {{ render_field(form.manufacturer_id) }}
    {{ render_field(form.model_id) }}
    {{ render_field(form.location_id) }}
    {{ render_field(form.status_id) }}
    {{ render_field(form.parent_id) }}
    {{ render_field(form.mac_addresses) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="button" class="btn btn-primary" id="clear">Clear</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/inventory/edit_item.html
{% extends "inventory/items.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Edit Item - CSEntry{% endblock %}

{% block items_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('inventory.view_item', ics_id=form.ics_id.data) }}">View item</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('inventory.edit_item', ics_id=form.ics_id.data) }}">Edit item</a>
    </li>
{% endblock %}


{% block items_main %}
  <form id="itemForm" method="POST">
    {{ form.hidden_tag() }}
    {% if form.ics_id.data.startswith(config['TEMPORARY_ICS_ID'])  or form.ics_id.errors %}
      {{ render_field(form.ics_id) }}
    {% else %}
      {{ render_field(form.ics_id, readonly=True) }}
    {% endif %}
    {{ render_field(form.serial_number) }}
    {{ render_field(form.quantity) }}
    {{ render_field(form.manufacturer_id) }}
    {{ render_field(form.model_id) }}
    {{ render_field(form.location_id) }}
    {{ render_field(form.status_id) }}
    {{ render_field(form.parent_id) }}
    {{ render_field(form.mac_addresses) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/inventory/items.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active %}

{% block title %}Items - CSEntry{% endblock %}

{% block main %}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/inventory/items")) }}" href="{{ url_for('inventory.list_items') }}">List items</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.startswith("/inventory/items/create")) }}" href="{{ url_for('inventory.create_item') }}">Register new item</a>
    </li>
    {% block items_nav %}{% endblock %}
  </ul>

  <br>

  {% block items_main %}
  <table id="items_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Id</th>
        <th>ICS id</th>
        <th>Created</th>
        <th>Updated</th>
        <th>Serial number</th>
        <th>Quantity</th>
        <th>Manufacturer</th>
        <th>Model</th>
        <th>Location</th>
        <th>Status</th>
        <th>Parent</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/items.js') }}"></script>
{% endblock %}

app/templates/inventory/qrcodes.html
{% extends "base-fluid.html" %}

{% block title %}QR Codes - CSEntry{% endblock %}

{% block main %}
  <ul class="nav nav-tabs">
    {% for item in ('Action', 'Manufacturer', 'Model', 'Location', 'Status') %}
    <li class="nav-item">
      <a class="nav-link {% if kind == item %}active{% endif %}" href="{{ url_for('inventory.qrcodes', kind=item) }}">{{ item }}</a>
    </li>
    {% endfor %}
  </ul>

  <br>

  <div class="row">
    {% for image in images %}
    <div class="col-md-3">
      <div class="card">
        <img class="card-img-top" src="data:image/png;base64,{{ image.data }}">
        <div class="card-body">
          <h4 class="card-title">{{ image.name }}</h4>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{%- endblock %}

app/templates/inventory/view_item.html
{% extends "inventory/items.html" %}
{% from "_helpers.html" import link_to_item, link_to_items, format_datetime, link_to_host %}

{% block title %}View Item - CSEntry{% endblock %}

{% block items_nav %}
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('inventory.view_item', ics_id=item.ics_id) }}">View item</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('inventory.edit_item', ics_id=item.ics_id) }}">Edit item</a>
    </li>
{% endblock %}

{% block items_main %}
  <dl class="row">
    <dt class="col-sm-3">ICS id</dt>
    <dd class="col-sm-9">{{ item.ics_id }}</dd>
    <dt class="col-sm-3">Created</dt>
    <dd class="col-sm-9">{{ format_datetime(item.created_at) }}</dd>
    <dt class="col-sm-3">Created by</dt>
    <dd class="col-sm-9">{{ item.user }}</dd>
    <dt class="col-sm-3">Updated</dt>
    <dd class="col-sm-9">{{ format_datetime(item.updated_at) }}</dd>
    <dt class="col-sm-3">Serial number</dt>
    <dd class="col-sm-9">{{ item.serial_number }}</dd>
    <dt class="col-sm-3">Quantity</dt>
    <dd class="col-sm-9">{{ item.quantity }}</dd>
    <dt class="col-sm-3">Manufacturer</dt>
    <dd class="col-sm-9">{{ item.manufacturer }}</dd>
    <dt class="col-sm-3">Model</dt>
    <dd class="col-sm-9">{{ item.model }}</dd>
    <dt class="col-sm-3">Location</dt>
    <dd class="col-sm-9">{{ item.location }}</dd>
    <dt class="col-sm-3">Status</dt>
    <dd class="col-sm-9">{{ item.status }}</dd>
    {% if item.host %}
    <dt class="col-sm-3">Host</dt>
    <dd class="col-sm-9">{{ link_to_host(item.host) }}</dd>
    {% endif %}
    {% for mac in item.macs %}
      {% set macloop = loop %}
      <dt class="col-sm-3">MAC Address{{ loop.index }}</dt>
      <dd class="col-sm-9">{{ mac.address }}</dd>
      {% for interface in mac.interfaces %}
        <dt class="col-sm-3">Interface{{ macloop.index }}-{{ loop.index }}</dt>
        <dd class="col-sm-9">IP: {{ interface.ip }} / name: {{ interface.name }}</dd>
      {% endfor %}
    {% endfor %}
    <dt class="col-sm-3">Parent</dt>
    <dd class="col-sm-9">{{ link_to_item(item.parent) }}</dd>
    <dt class="col-sm-3">Children</dt>
    <dd class="col-sm-9">{{ link_to_items(item.children) }}</dd>
  </dl>

  <h4>Comments</h4>
  {% for comment in item.comments | sort(attribute='created_at') %}
  <div class="card border-light mb-3">
    <div class="card-header">
      {{ comment.user }} commented on {{ format_datetime(comment.created_at) }}
    </div>
    <div class="card-body item-comment">{{ comment.body }}</div>
  </div>
  {% endfor %}
  {% block comment_item %}
  <a class="btn btn-primary" href="{{ url_for('inventory.comment_item', ics_id=item.ics_id) }}#body">Comment</a>
  {% endblock %}

  <hr>

  <h4>History</h4>
  <table id="item_version_table" class="table table-hover table-sm">
    <thead>
      <tr>
        <th>Updated</th>
        <th>Quantity</th>
        <th>Location</th>
        <th>Status</th>
        <th>Parent</th>
      </tr>
    </thead>
    <tbody>
      {% for version in item.history() %}
      <tr>
        <td>{{ version['updated_at'] }}</td>
        <td>{{ version['quantity'] }}</td>
        <td>{{ version['location'] }}</td>
        <td>{{ version['status'] }}</td>
        <td>{{ link_to_item(version['parent']) }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%- endblock %}