app/main/views.py
# -*- coding: utf-8 -*-
"""
app.main.views
~~~~~~~~~~~~~~

This module implements the main blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from flask import Blueprint, render_template, jsonify
from flask_login import login_required
from .. import utils

bp = Blueprint('main', __name__)


# Declare custom error handlers for all views
@bp.app_errorhandler(404)
def not_found_error(error):
    return render_template('404.html'), 404


@bp.app_errorhandler(500)
def internal_error(error):
    return render_template('500.html'), 500


@bp.app_errorhandler(utils.CSEntryError)
def handle_csentry_error(error):
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response


@bp.route('/')
@login_required
def index():
    return render_template('index.html')

app/network/views.py
# -*- coding: utf-8 -*-
"""
app.network.views
~~~~~~~~~~~~~~~~~

This module implements the network blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
import ipaddress
import sqlalchemy as sa
from flask import (Blueprint, render_template, jsonify, session,
                   redirect, url_for, request, flash, current_app)
from flask_login import login_required
from .forms import (HostForm, InterfaceForm, HostInterfaceForm, NetworkForm,
                    NetworkScopeForm)
from ..extensions import db
from ..decorators import login_groups_accepted
from .. import models, utils, helpers

bp = Blueprint('network', __name__)


@bp.route('/hosts')
@login_required
def list_hosts():
    return render_template('network/hosts.html')


@bp.route('/hosts/create', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def create_host():
    # Try to get the network_id from the session
    # to pre-fill the form with the same network
    try:
        network_id = session['network_id']
    except KeyError:
        # No need to pass request.form when no extra keywords are given
        form = HostInterfaceForm()
    else:
        form = HostInterfaceForm(request.form, network_id=network_id)
    # Remove the host_id field inherited from the InterfaceForm
    # It's not used in this form
    del form.host_id
    if form.validate_on_submit():
        network_id = form.network_id.data
        host = models.Host(name=form.name.data,
                           type=form.type.data,
                           description=form.description.data or None,
                           item_id=form.item_id.data)
        # The total number of tags will always be quite small
        # It's more efficient to retrieve all of them in one query
        # and do the filtering here
        all_tags = models.Tag.query.all()
        tags = [tag for tag in all_tags if str(tag.id) in form.tags.data]
        interface = models.Interface(name=form.interface_name.data,
                                     ip=form.ip.data,
                                     network_id=network_id,
                                     tags=tags)
        interface.cnames = [models.Cname(name=name) for name in form.cnames_string.data.split()]
        helpers.associate_mac_to_interface(form.mac_address.data, interface)
        host.interfaces = [interface]
        current_app.logger.debug(f'Trying to create: {host!r}')
        db.session.add(host)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Host {host} created!', 'success')
        # Save network_id to the session to retrieve it after the redirect
        session['network_id'] = network_id
        return redirect(url_for('network.create_host'))
    return render_template('network/create_host.html', form=form)


@bp.route('/hosts/view/<name>')
@login_required
def view_host(name):
    host = models.Host.query.filter_by(name=name).first_or_404()
    return render_template('network/view_host.html', host=host)


@bp.route('/hosts/edit/<name>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def edit_host(name):
    host = models.Host.query.filter_by(name=name).first_or_404()
    form = HostForm(request.form, obj=host)
    if form.validate_on_submit():
        host.name = form.name.data
        host.type = form.type.data
        host.item_id = form.item_id.data
        host.description = form.description.data or None
        current_app.logger.debug(f'Trying to update: {host!r}')
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Host {host} updated!', 'success')
        return redirect(url_for('network.view_host', name=host.name))
    return render_template('network/edit_host.html', form=form)


@bp.route('/interfaces/create/<hostname>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def create_interface(hostname):
    host = models.Host.query.filter_by(name=hostname).first_or_404()
    form = InterfaceForm(request.form, host_id=host.id, interface_name=host.name)
    if form.validate_on_submit():
        # The total number of tags will always be quite small
        # It's more efficient to retrieve all of them in one query
        # and do the filtering here
        all_tags = models.Tag.query.all()
        tags = [tag for tag in all_tags if str(tag.id) in form.tags.data]
        interface = models.Interface(host_id=host.id,
                                     name=form.interface_name.data,
                                     ip=form.ip.data,
                                     network_id=form.network_id.data,
                                     tags=tags)
        interface.cnames = [models.Cname(name=name) for name in form.cnames_string.data.split()]
        helpers.associate_mac_to_interface(form.mac_address.data, interface)
        current_app.logger.debug(f'Trying to create: {interface!r}')
        db.session.add(interface)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Host {interface} created!', 'success')
        return redirect(url_for('network.create_interface', hostname=hostname))
    return render_template('network/create_interface.html', form=form, hostname=hostname)


@bp.route('/interfaces/edit/<name>', methods=('GET', 'POST'))
@login_groups_accepted('admin', 'create')
def edit_interface(name):
    interface = models.Interface.query.filter_by(name=name).first_or_404()
    cnames_string = ' '.join([str(cname) for cname in interface.cnames])
    try:
        mac_address = interface.mac.address
    except AttributeError:
        mac_address = ''
    form = InterfaceForm(request.form, obj=interface,
                         interface_name=interface.name,
                         mac_address=mac_address,
                         cnames_string=cnames_string)
    ips = [interface.ip]
    ips.extend([str(address) for address in interface.network.available_ips()])
    form.ip.choices = utils.get_choices(ips)
    if form.validate_on_submit():
        interface.name = form.interface_name.data
        interface.ip = form.ip.data
        interface.network_id = form.network_id.data
        if form.mac_address.data:
            if form.mac_address.data != mac_address:
                # The MAC changed - add the new one to the interface
                # that will remove the association to the previous one
                helpers.associate_mac_to_interface(form.mac_address.data, interface)
            # else: nothing to do (address didn't change)
        else:
            # No MAC associated
            interface.mac_id = None
        # Delete the cnames that have been removed
        new_cnames_string = form.cnames_string.data.split()
        for (index, cname) in enumerate(interface.cnames):
            if cname.name not in new_cnames_string:
                current_app.logger.debug(f'Deleting cname: {cname}')
                # Removing the cname from interface.cnames list will
                # delete it from the database due to the cascade
                # delete-orphan option defined on the model
                del interface.cnames[index]
        # Add new cnames
        for name in new_cnames_string:
            if name not in cnames_string:
                cname = models.Cname(name=name)
                current_app.logger.debug(f'Creating cname: {cname}')
                interface.cnames.append(cname)
        all_tags = models.Tag.query.all()
        tags = [tag for tag in all_tags if str(tag.id) in form.tags.data]
        interface.tags = tags
        current_app.logger.debug(f'Trying to update: {interface!r}')
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f'{e}')
            flash(f'{e}', 'error')
        else:
            flash(f'Interface {interface} updated!', 'success')
        return redirect(url_for('network.view_host', name=interface.host.name))
    return render_template('network/edit_interface.html', form=form, hostname=interface.host.name)


@bp.route('/interfaces/delete', methods=['POST'])
@login_groups_accepted('admin', 'create')
def delete_interface():
    interface = models.Interface.query.get_or_404(request.form['interface_id'])
    hostname = interface.host.name
    # Deleting the interface will also delete all
    # associated cnames due to the cascade delete option
    # defined on the model
    db.session.delete(interface)
    db.session.commit()
    flash(f'Interface {interface.name} has been deleted', 'success')
    return redirect(url_for('network.view_host', name=hostname))


@bp.route('/scopes')
@login_required
def list_scopes():
    return render_template('network/scopes.html')


@bp.route('/scopes/create', methods=('GET', 'POST'))
@login_groups_accepted('admin')
def create_scope():
    form = NetworkScopeForm()
    if form.validate_on_submit():
        scope = models.NetworkScope(name=form.name.data,
                                    description=form.description.data or None,
                                    first_vlan=form.first_vlan.data,
                                    last_vlan=form.last_vlan.data,
                                    supernet=form.supernet.data)
        current_app.logger.debug(f'Trying to create: {scope!r}')
        db.session.add(scope)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()

app/user/views.py
# -*- coding: utf-8 -*-
"""
app.user.views
~~~~~~~~~~~~~~

This module implements the user blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from flask import (Blueprint, render_template, request, redirect, url_for,
                   flash, current_app, session)
from flask_login import login_user, logout_user, login_required, current_user
from flask_ldap3_login.forms import LDAPLoginForm
from .forms import TokenForm
from ..extensions import cache, db
from ..models import load_user
from .. import tokens, utils

bp = Blueprint('user', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LDAPLoginForm(request.form)
    if form.validate_on_submit():
        login_user(form.user, remember=form.remember_me.data)
        return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('user/login.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    # Don't forget to remove the user from the cache
    cache.delete_memoized(load_user, str(current_user.id))
    logout_user()
    return redirect(url_for('user.login'))


@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if current_user not in db.session:
        # If the current user is cached, it won't be in the sqlalchemy session
        # Add it to access the user.tokens relationship in the template
        db.session.add(current_user)
    # Try to get the generated token from the session
    token = session.pop('generated_token', None)
    form = TokenForm(request.form)
    if form.validate_on_submit():
        token = tokens.generate_access_token(identity=current_user.id,
                                             expires_delta=False,
                                             description=form.description.data)
        # Save token to the session to retrieve it after the redirect
        session['generated_token'] = token
        flash('Make sure to copy your new personal access token now. You won’t be able to see it again!', 'success')
        return redirect(url_for('user.profile'))
    return render_template('user/profile.html',
                           form=form,
                           user=current_user,
                           generated_token=token)


@bp.route('/tokens/revoke', methods=['POST'])
@login_required
def revoke_token():
    token_id = request.form['token_id']
    jti = request.form['jti']
    try:
        tokens.revoke_token(token_id, current_user.id)
    except utils.CSEntryError as e:
        current_app.logger.warning(e)
        flash(f'Could not revoke the token {jti}. Please contact an administrator.', 'error')
    else:
        flash(f'Token {jti} has been revoked', 'success')
    return redirect(url_for('user.profile'))

app/templates/_helpers.html
{% macro is_active(active) -%}
{% if active %}active{% endif %}
{%- endmacro %}

{% macro link_to_host(name) -%}
  <a href="{{ url_for('network.view_host', name=name) }}">{{ name }}</a>
{%- endmacro %}

{% macro link_to_item(ics_id) -%}
  {% if ics_id %}
    <a href="{{ url_for('inventory.view_item', ics_id=ics_id) }}">{{ ics_id }}</a>
  {% else %}
    {{ ics_id }}
  {% endif %}
{%- endmacro %}

{% macro link_to_items(ics_ids) -%}
  {% for ics_id in ics_ids %}
    {{ link_to_item(ics_id) }}
  {% endfor %}
{%- endmacro %}

{% macro render_field(field) -%}
  {% set field_class = kwargs.pop('class_', '') + ' form-control' %}
  {% if field.errors %}
    {% set field_class = field_class + ' is-invalid' %}
  {% endif %}

  <div class="form-group row">
    {{ field.label(class_="col-sm-2 col-form-label") }}
    <div class="col-sm-10">
      {{ field(class_=field_class, **kwargs) }}
      {% if field.description %}
        <small class="form-text text-muted">
          {{ field.description|safe }}
        </small>
      {% endif %}
      {% if field.errors %}
        <div class="invalid-feedback">
          {{ field.errors|join(' / ') }}
        </div>
      {% endif %}
    </div>
  </div>
{%- endmacro %}

{% macro format_datetime(dt) -%}
  {{ dt.strftime("%Y-%m-%d %H:%M") }}
{%- endmacro %}

{% macro delete_button_with_confirmation(title, modal_id, message) -%}
  <button type="button" class="btn btn-light" data-toggle="modal" data-target={{ "#%s" | format(modal_id) }}>
    <span class="oi oi-trash" title="{{ title }}" aria-hidden="true"></span>
  </button>
  <!-- Modal -->
  <div class="modal fade" id="{{ modal_id }}" tabindex="-1" role="dialog" aria-labelledby="delete-confirmation" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title">{{ message }}</h6>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">OK</button>
        </div>
      </div>
    </div>
  </div>
{%- endmacro %}

app/templates/base-fluid.html
{% extends "base.html" %}
{% from "_helpers.html" import is_active %}

{# overwrite the base content block to use container-fluid instead of container #}
{% block content %}
<div class="container-fluid">
  <div class="row">

    <div class="col-12 col-md-2 col-xl-2">
      {% set path = request.path %}
      <div class="list-group">
        {% if path.startswith("/inventory") %}
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/inventory/items")) }}"
          href="{{ url_for('inventory.list_items') }}">Items</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/inventory/attributes")) }}"
          href="{{ url_for('inventory.attributes', kind='Manufacturer') }}">Attributes</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/inventory/qrcodes")) }}"
          href="{{ url_for('inventory.qrcodes', kind='Action') }}">QR Codes</a>
        {% elif path.startswith("/network") %}
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith(("/network/hosts", "/network/interfaces"))) }}"
          href="{{ url_for('network.list_hosts') }}">Hosts</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/network/networks")) }}"
          href="{{ url_for('network.list_networks') }}">Networks</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/network/scopes")) }}"
          href="{{ url_for('network.list_scopes') }}">Network Scopes</a>
        {% endif %}
      </div>
    </div>

    <div class="col-12 col-md-10 col-xl-10">
      {{utils.flashed_messages(messages, container=False, dismissible=True)}}
      {% block main %}{% endblock %}
    </div>

  </div>
</div>
{% endblock %}

app/templates/base.html
{%- extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}
{% from "_helpers.html" import is_active %}

{% block styles %}
  {{super()}}
  <link href="{{ url_for('static', filename='css/open-iconic-bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/csentry.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}CSEntry{% endblock %}

{% block navbar %}
  <!-- Fixed navbar -->
  <div class="navbar fixed-top navbar-expand-lg navbar-light bg-light" role="navigation">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">CSEntry</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto">
          {% set path = request.path %}
          <a class="nav-item nav-link {{ is_active(path.startswith("/inventory")) }}" href="{{ url_for('inventory.list_items') }}">Inventory</a>
          <a class="nav-item nav-link {{ is_active(path.startswith("/network")) }}" href="{{ url_for('network.list_hosts') }}">Network</a>
          {% if current_user.is_authenticated and current_user.is_admin %}
            <a class="nav-item nav-link" href="{{ url_for('admin.index') }}">Admin</a>
          {% endif %}
        </div>
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <div class="dropdown {{ is_active(path == "/user/profile") }}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{current_user}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('user.profile') }}">Profile</a>
              <a class="dropdown-item" href="{{ url_for('user.logout') }}">Logout</a>
            </div>
          </div>
          {% endif %}
          {% block navbar_right %}{% endblock %}
        </div>
      </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    {{utils.flashed_messages(messages, container=False, dismissible=True)}}
    {% block main %}{% endblock %}
  </div>
{% endblock %}

{% block scripts %}
  {{super()}}
  <script src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/clipboard.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/showdown.min.js') }}"></script>
  <script type=text/javascript>
    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
  </script>
  {% block csentry_scripts %}{% endblock %}
{% endblock %}

app/templates/index.html
{%- extends "base.html" %}

{% block main %}
  <div class="jumbotron">
    <h1 class="display-4">Welcome to CSEntry!</h1>
    <p class="lead">Control System Entry allows you to easily register items and network devices.</lead>
  </div>
{%- endblock %}